[[main]]
  identifier = 'home'
  name = 'Home'
  pageref = '/'
  weight = -300

[[main]]
  weight = -289
  #parent = 'classes'
  # weight = 300
  identifier = 'material'
  name = 'Material'
  pageref = '/material'

##
## Classes
##

[[main]]
  identifier = 'classes'
  name = 'Classes'
  pageref = '/classes'
  weight = -290
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023/info3'
  name = 'B 15 Informatik 3'
  pageref = '/classes/ss2023/info3'
  weight = 5
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023/aep'
  name = 'B 20.1 Auswertung von Erfahrungen am Praxisplatz'
  pageref = '/classes/ss2023/aep'
  weight = 10
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023/m1-web'
  name = 'M 1 Mediaprogramming'
  pageref = '/classes/ss2023/m1-web'
  weight = 20
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023/masterseminar'
  name = 'M 17.1 Masterseminar'
  pageref = '/classes/ss2023/masterseminar'
  weight = 25

[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023/theses'
  name = 'Theses'
  pageref = '/classes/ss2023/theses'
  weight = 35
[[main]]
  parent = 'classes'
  identifier = '/classes/ss2023'
  name = 'All SoSe 2023'
  pageref = '/classes/ss2023'
  weight = 40
[[main]]
  parent = 'classes'
  identifier = '/classes/'
  name = 'All Classes'
  pageref = '/classes'
  weight = 50

  ##
  ## Other
  ##




[[main]]
  identifier = 'studies'
  name = 'Studies'
  pageref = '/studies'
  weight = -170

[[main]]
parent = 'studies'
identifier = '/studies/thesis/'
name = 'Thesis'
pageref = '/studies/thesis'
weight = 10
[[main]]
parent = 'studies'
identifier = '/studies/ic/'
name = 'IC'
pageref = '/studies/ic'
weight = 20
[[main]]
parent = 'studies'
identifier = '/studies/grading/'
name = 'Grading Info'
pageref = '/studies/grading'
weight = 30


[[main]]
  identifier = 'software_projects'
  name = 'Software Projects'
  pageref = '/software_projects'
  weight = -175

[[main]]
  identifier = 'misc'
  name = 'Misc'
  pageref = '/misc'
  weight = -150



[[main]]
  identifier = 'contact'
  name = 'Contact Info'
  pageref = '/contact'
  weight = -140
