name: Deploy Staging

on:
  push:
    branches:
      - hugo_migration  # Set a branch to deploy
    tags-ignore:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: |
          cd hugo
          hugo --minify -e staging
          cd ..

      - name: Push to Staging website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'hugo/public'
          destination-github-username: 'bkleinen'
          destination-repository-name: 'website-staging'
          user-email: barne.kleinen@htw-berlin.de
          target-branch: hugo_staging
