name: Deploy HTW

on:
  push:
    branches:
      - hugo_migration  # Set a branch to deploy
    tags-ignore:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        env:
          WEBSSHKEY: ${{ secrets.WEBSSHKEY }}
          HOST1: ${{ secrets.HOST1 }}
          HOST2: ${{ secrets.HOST2 }}
        run: |
          if ["$HOST1" == ""]; then
            echo "HOST1 not set; doing nothing and am happy about that"
          else
            hugo  --source hugo --destination ../public-htw --environment htw --baseURL https://home.htw-berlin.de/~kleinen/hugo

            eval $(ssh-agent -s)
            ssh-add - <<< "$WEBSSHKEY"

            ssh -o StrictHostKeyChecking=no $HOST1 "mkdir -p ~/hugo-tunnel"
            scp -r -o StrictHostKeyChecking=no  ./public-htw/* $HOST1:~/hugo-tunnel > /dev/null

            scp -r -o StrictHostKeyChecking=no  _bin/hugo_deployment/steps.sh $HOST1:~/hugo-tunnel/steps.sh
            echo $WEBSSHKEY | ssh -o StrictHostKeyChecking=no $HOST1 'cat >>  ~/.tmp; chmod 600  ~/.tmp'
            ssh -o StrictHostKeyChecking=no $HOST1 "export set HOST2=$HOST2; . ~/hugo-tunnel/steps.sh" 2>&1
            eval "$(ssh-agent -k)"
          fi
