name: Hugo broken link check

on:
  push:
    branches:
      - 23s

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Hugo Internal Broken Link Checker
      uses: bkleinen/hugo-broken-link-checker@v1.1.0
      with:
        hugo-source: hugo
